export const DHAKA_AREAS = [
  'Badda',
  'Banani',
  'Bashundhara',
  'Dhanmondi',
  'Farmgate',
  'Gulshan',
  'Jatrabari',
  'Khilgaon',
  'Mirpur',
  'Mohakhali',
  'Mohammadpur',
  'Motijheel',
  'Paltan',
  'Rampura',
  'Tejgaon',
  'Uttara',
  'Wari',
] as const;